services:
  postgres:
    container_name: nest-clean-pg
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: nest-clean
      PGDATA: /data/postgres
    volumes:
      - ./data/pg:/data/postgres

  cache:
    container_name: nest-clean-cache
    image: redis
    ports:
      - 6379:6379
    volumes:
      - ./data/redis:/data

  q-n-a-forum-api:
    container_name: q-n-a-forum-api
    build:
      context: .
    ports:
      - 3333:3333
    depends_on:
      - postgres
      - cache
    environment:
      - DATABASE_URL=postgresql://postgres:docker@nest-clean-pg:5432/nest-clean?schema=public
      - REDIS_HOST=nest-clean-cache